feat: batched data upload
zeno-ml/zeno-client pull request #23
Opened 2023-10-02 04:07 UTC by cabreraalex

# Description
Use record batches and multiple POST requests to upload large files.

2023-10-03 07:10 UTC, Sparkier requested changes

2023-10-03 18:47 UTC, Sparkier approved these changes
Need to clean up the notebooks and remove outputs but otherwise good.

2023-10-03 18:47 UTC, Sparkier commented on zeno_client/client.py
> +        label_column: Optional[str] = "",
Maybe default should be None then? Not sure.

2023-10-04 00:32 UTC, cabreraalex commented
Waiting to merge until refactor is in prod

2023-10-04 13:59 UTC, merged